### PR TITLE
Add cpp-linter download stats badge

### PR DESCRIPTION
**Pull request by shenxianpeng**
Just want to know how many times cpp-linter has been downloaded every week.

### CODE REVIEW

**Comment by 2bndy5** [comment]
We could track the number of downloads per version using https://pepy.tech/project/cpp-linter which also gives a monthly and all-time totals.

**Comment by shenxianpeng** [comment]
OK, let's me change the link to https://img.shields.io/pypi/dm/cpp-linter, I like this one.

**Comment by 2bndy5** [comment]
what about [](https://img.shields.io/pypi/dm/cpp-linter?label=PyPI%20Downloads), So it is clear that these are downloads from PyPI (not from Github)

**Comment by shenxianpeng** [comment]
Nice!

**Comment by shenxianpeng** [comment]
Updated

**Comment by 2bndy5** [comment]
we could even add a logo... [](https://img.shields.io/pypi/dw/cpp-linter?label=PyPI%20Downloads&logo=python&logoColor=white)

**Review by 2bndy5 — APPROVED** [review]

**Comment by 2bndy5** [comment]
On second thought, I think green color makes the text hard to read

**Comment by 2bndy5** [comment]
dark green is easier to read: [](https://img.shields.io/pypi/dw/cpp-linter?color=dark-green&label=PyPI%20Downloads&logo=python&logoColor=white)

**Comment by shenxianpeng** [comment]
Done :)

**Review by 2bndy5 — APPROVED** [review]

**Comment by shenxianpeng** [comment]
I remembered why I did not use https://pepy.tech/project/cpp-linter instead of https://pypistats.org/packages/cpp-linter
Because date in badge [](https://img.shields.io/pypi/dw/cpp-linter?color=dark-green&label=PyPI%20Downloads&logo=python&logoColor=white) is different with the data on https://pepy.tech/project/cpp-linter which is 416

If we used the badge [Downloads](https://pepy.tech/project/cpp-linter) from pepy.tech, it seems does not support logo, logoColor, etc.

**Comment by shenxianpeng** [comment]
I can create a similar badge from pepy.tech, but it does not support to add a logo. 

[Downloads](https://pepy.tech/project/cpp-linter)

Maybe we have to use `https://img.shields.io/badge/dynamic/json` to create a custom badge if needed.

**Comment by 2bndy5** [comment]
I noticed you didn't use the customized badge from pepy tech... I'm ok with how it is now.

I think there's a way to embed a custom logo using a base64 string in img.io badges, but it seems a fragile.

**Comment by 2bndy5** [comment]
Got it to work finally! [](https://img.shields.io/github/license/cpp-linter/cpp-linter?color=dark-green&logo=data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAA4AAAAOCAYAAAAfSC3RAAABhWlDQ1BJQ0MgcHJvZmlsZQAAKJF9kT1Iw0AYht+mlapUHOwg6pChOlkQ/3CUKhbBQmkrtOpgcumP0KQhSXFxFFwLDv4sVh1cnHV1cBUEwR8QRycnRRcp8buk0CLGO457eO97X+6+A4R6malmYAxQNctIxWNiNrciBl/RhQDNKQxKzNQT6YUMPMfXPXx8v4vyLO+6P0ePkjcZ4BOJZ5luWMTrxNObls55nzjMSpJCfE48atAFiR+5Lrv8xrnosMAzw0YmNUccJhaLbSy3MSsZKvEkcURRNcoXsi4rnLc4q+Uqa96TvzCU15bTXKc1hDgWkUASImRUsYEyLERp10gxkaLzmId/wPEnySWTawOMHPOoQIXk+MH/4HdvzcLEuJsUigEdL7b9MQwEd4FGzba/j227cQL4n4ErreWv1IGZT9JrLS1yBPRuAxfXLU3eAy53gP4nXTIkR/LTEgoF4P2MvikH9N0C3atu35rnOH0AMtSrpRvg4BAYKVL2mse7O9v79m9Ns38/gXVyrQ+gLmQAAAAGYktHRAAAAAAAAPlDu38AAAAJcEhZcwAACxMAAAsTAQCanBgAAAAHdElNRQfmCQQFBg45ku9zAAAAGXRFWHRDb21tZW50AENyZWF0ZWQgd2l0aCBHSU1QV4EOFwAAAXRJREFUKM+V0r9rFEEcBfDPHCHgVmdjJRLBIhKLi4FgtexhYQgcpLC0uPsPjKAptpRDRFBE+8RCUCwucHXwWCxFDEJQ0mhnKj2LbcdmDpbFxmmGee/73vfHfIP/PMV0PITQBGOVXcMe+jhN8B9MQl4fFNPxI2yhHxqiIZ5hN+T1Qcvwan9ePsAObswG5belRGwkURHy+rhdXn9ebmH4+NzJvc3lyVlAJ3FPcLs/L0MxHe+0etrGU9zdXJ78wgvoxCrr4lLI6yOs4m0xHfeSqIvXOJwNyud4hTuxyrod9DCD2aB8gx/YL6bjDO9S4hGEvI6o0FtKxLxR3X0c4gPWMZoNyt8N/jyEWGUBn0Jerzf6+ogNnMwG5VpjuhdwhsudlP5zrLLrDdeH6d5tDXgPxyGvvy+cVmKVvU+DWmRdaf3lMFZZjFV2S4vIY5WdpoBuA1+LVbafRKMF3l65VbzEzVaJX9JGHf1T2DC4iCvp+TPk9dd2zF+kwouCxjQxLAAAAABJRU5ErkJggg==)

**Comment by 2bndy5** [comment]
FYI, I had to resize the logo to 14 px logo_small and encode it using [this site](https://www.base64encoder.io/image-to-base64-converter/).

**Pull request merged**
